<a href="https://colab.research.google.com/github/sagar2582/TensorFlow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Covering fundamentals of tensors using TensorFlow

* Intro to Tensors
* Getting information from Tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function
* Using GPU's with TensorFlow

## Intro to Tensors

In [62]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [63]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [64]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [65]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [66]:
# check dimension of vector
vector.ndim

1

In [67]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [68]:
matrix.ndim

2

In [69]:
# Create another matrxi

matrix_1 = tf.constant([[10.,7.],
                        [3.,2.],
                        [6.,8.]], dtype = tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 6.,  8.]], dtype=float16)>

In [70]:
matrix_1.ndim

2

In [71]:
# let's create a Tensor
tensor = tf.constant([[[1,2,4],
                       [4,5,6]],
                     [[7,8,6],
                      [10,3,34]],
                     [[34,45,15],
                      [16,14,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  4],
        [ 4,  5,  6]],

       [[ 7,  8,  6],
        [10,  3, 34]],

       [[34, 45, 15],
        [16, 14,  4]]], dtype=int32)>

In [72]:
tensor.ndim # dimensions of tensor

3

* Scalar is a single number 
* vector is a number with direction
* A mtrix is a 2D array of numbers 
* Tensor is an n-dimensional array of number

### Creating a tf.variable()

In [73]:
# Create the same tensor with same tf.varible() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [74]:
# let's try changing one of the elements in the changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Lets's try changing the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random Tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [75]:
# Create two random tensors (but same)
random_1 = tf.random.Generator.from_seed(42) # Set seed forreproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [76]:
random_2 = tf.random.Generator.from_seed(42) # Chnage the seed to a random number and the randomness of the numbers will change rather than getting the o/p again
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### shuffling the order of elements in the tensors

In [77]:
# Shuffle a tensor (This is important for when you want to shuffle your data so the inherant data doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [5,1],
                            [8,4]])
# Shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled) # Shuffled along it's 1st dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  4],
       [ 5,  1],
       [10,  7]], dtype=int32)>

In [78]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  1],
       [10,  7],
       [ 8,  4]], dtype=int32)>

In [79]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  4],
       [10,  7],
       [ 5,  1]], dtype=int32)>

In [80]:
tf.random.set_seed = 42
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  1],
       [ 8,  4]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed generation : https://www.tensorflow.org/api_docs/python/tf/random/set_seed
and practice writing 5 random tensors and shuffle them .

> Rule: to make reproducable experiments, shuffle you data with a similar random seed for global and funtion level.

In [81]:
tf.random.set_seed = 42
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  1],
       [ 8,  4]], dtype=int32)>

### Other ways to make tensors

In [82]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [83]:
# Creating a Tensor of all Zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [84]:
# Turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix)   --- Capital for Tensors
# y = tf.constant(vector)        --- Non-Capitla for Vectors

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [85]:
A = tf.constant(numpy_A, shape=(2,3,4))  # Conerted to Tensor
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting informations from Tensors

* Shape  - tensor.shape - The length(number of elements) of each of the dimensions of a tensor 
* Rank   - tensor.ndim - Number of dimensions
* Axis/dimension - A particular dimension of a tensor - tensor[0], tensor[:,1]
* Size - tf.size(tensor) - total number of itmes in a tensor

In [86]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor =  tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [87]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [88]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [89]:
# Getting various attributes of our tensor
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


 ## Indexing tensors

 Tensors can be indexed just like Python lists.

In [90]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [91]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [92]:
# Last iten of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [93]:
# Add in extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [94]:
# Alternativer to tf.axis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand on the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [95]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand on the )th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors (Tensor operations)

**Basic Operation**
`+`,`-`,`*`,`/`

In [96]:
# Tensor addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [97]:
# Same for multiplication, Substraction(can go in minus) and Division
# Or for multiplication we can use the inbuilt function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**


In [98]:
# Matrix multiplication in TensorFlow
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [99]:
tf.matmul(tensor, tensor)   # Dot Product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [100]:
# Matrix Multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [101]:
tensor.shape

TensorShape([2, 2])

In [102]:
X = tf.constant([[1,2],
                 [3,4],
                 [4,5]])
Y = tf.constant([[6,7],
                 [8,9],
                 [10,11]])
# Y = tf.reshape(Y, shape=(2, 3))
# X, Y

In [103]:
# tf.matmul(X, Y)

In [104]:
# X @ Y

In [105]:
# Transpose
# tf.transpose(X)

**The dot product**
Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [106]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 70,  78],
       [ 94, 105]], dtype=int32)>

In matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) the matrix

### Changing the Data type of a tensor

In [107]:
# Create a new tensor with default datatype (float32 - depends on the data inside of your tensor)
B = tf.constant([1.7,7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [108]:
# Change from Float32 - float16 (reduced precision)
C = tf.cast(B, dtype=tf.float16)
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

get all the absolute value   - >  tf.abs(tensor)

get the minimum -> tf.reduce_min(tensor)

get the maximum - > tf.reduce_max(tensor)

get the mean -> tf.reduce_mean(tensor)

get the sum -> tf.reduce_sum(tensor)

In [109]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 32,  9, 19, 14, 55, 18,  8, 30, 70, 49, 87, 55, 85, 90, 73, 45,
       95, 72, 34, 44, 67, 79, 98,  6,  3, 27, 78,  8, 39, 45, 66, 44, 55,
       26, 54, 42, 64, 78, 50, 86, 75,  8, 49, 82, 38, 68, 34,  9, 82])>

In [110]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [111]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [112]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [113]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [114]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2531>

In [115]:
# Find the variance of the tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=754>

In [116]:
# Find standard deviation
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.456795>

##Find the positional maximum and minimum of a tensor

In [122]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed = 42
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.8140106 , 0.56050086, 0.65529776, 0.07779074, 0.2916286 ,
       0.869346  , 0.85293543, 0.74488413, 0.23167038, 0.9373425 ,
       0.01423836, 0.6969203 , 0.6470159 , 0.83223116, 0.8985163 ,
       0.8968816 , 0.06170475, 0.65055895, 0.38375092, 0.03270578,
       0.6914389 , 0.2645614 , 0.15980446, 0.4211502 , 0.42742312,
       0.5960679 , 0.9289441 , 0.7008066 , 0.44248593, 0.7198869 ,
       0.08909214, 0.69794965, 0.1742028 , 0.5656707 , 0.00978267,
       0.69514966, 0.620937  , 0.6576264 , 0.28910053, 0.28572774,
       0.35557103, 0.6427115 , 0.03321791, 0.5863534 , 0.271482  ,
       0.87123406, 0.6622138 , 0.8911326 , 0.66853416, 0.8215797 ],
      dtype=float32)>

In [123]:
# Find positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [124]:
# Index in our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9373425>

In [125]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9373425>

In [126]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [127]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [129]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009782672>

### Squeezing a tensor to get started


In [132]:
# Create a tensor to get started 
tf.random.set_seed=42
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.609717  , 0.8884362 , 0.02523851, 0.166188  , 0.7605015 ,
           0.42608535, 0.909992  , 0.6824695 , 0.9124968 , 0.29284072,
           0.7769941 , 0.3946725 , 0.29833007, 0.8244529 , 0.02987134,
           0.83319056, 0.21182394, 0.4288305 , 0.5798781 , 0.25579333,
           0.5021453 , 0.28902233, 0.83095646, 0.53160083, 0.85628057,
           0.98558533, 0.32661211, 0.48624277, 0.7538328 , 0.9797418 ,
           0.6482707 , 0.04165721, 0.5073401 , 0.9693073 , 0.42294896,
           0.39630997, 0.7018206 , 0.7221924 , 0.04950595, 0.15015674,
           0.6114718 , 0.1349603 , 0.3192916 , 0.21704102, 0.8897456 ,
           0.9141164 , 0.2166003 , 0.14763427, 0.41940963, 0.55586183]]]]],
      dtype=float32)>

In [133]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [135]:
G_squeezed = tf.squeeze(G)        # Removes the extra 1-dimension in you tensor
G_squeezed, G_squeezed.shape 

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.609717  , 0.8884362 , 0.02523851, 0.166188  , 0.7605015 ,
        0.42608535, 0.909992  , 0.6824695 , 0.9124968 , 0.29284072,
        0.7769941 , 0.3946725 , 0.29833007, 0.8244529 , 0.02987134,
        0.83319056, 0.21182394, 0.4288305 , 0.5798781 , 0.25579333,
        0.5021453 , 0.28902233, 0.83095646, 0.53160083, 0.85628057,
        0.98558533, 0.32661211, 0.48624277, 0.7538328 , 0.9797418 ,
        0.6482707 , 0.04165721, 0.5073401 , 0.9693073 , 0.42294896,
        0.39630997, 0.7018206 , 0.7221924 , 0.04950595, 0.15015674,
        0.6114718 , 0.1349603 , 0.3192916 , 0.21704102, 0.8897456 ,
        0.9141164 , 0.2166003 , 0.14763427, 0.41940963, 0.55586183],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors