<a href="https://colab.research.google.com/github/sagar2582/TensorFlow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Covering fundamentals of tensors using TensorFlow

* Intro to Tensors
* Getting information from Tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function
* Using GPU's with TensorFlow

## Intro to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimension of vector
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrxi

matrix_1 = tf.constant([[10.,7.],
                        [3.,2.],
                        [6.,8.]], dtype = tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 6.,  8.]], dtype=float16)>

In [9]:
matrix_1.ndim

2

In [10]:
# let's create a Tensor
tensor = tf.constant([[[1,2,4],
                       [4,5,6]],
                     [[7,8,6],
                      [10,3,34]],
                     [[34,45,15],
                      [16,14,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  4],
        [ 4,  5,  6]],

       [[ 7,  8,  6],
        [10,  3, 34]],

       [[34, 45, 15],
        [16, 14,  4]]], dtype=int32)>

In [11]:
tensor.ndim # dimensions of tensor

3

* Scalar is a single number 
* vector is a number with direction
* A mtrix is a 2D array of numbers 
* Tensor is an n-dimensional array of number

### Creating a tf.variable()

In [14]:
# Create the same tensor with same tf.varible() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# let's try changing one of the elements in the changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [17]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
# Lets's try changing the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random Tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [21]:
# Create two random tensors (but same)
random_1 = tf.random.Generator.from_seed(42) # Set seed forreproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42) # Chnage the seed to a random number and the randomness of the numbers will change rather than getting the o/p again
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### shuffling the order of elements in the tensors

In [24]:
# Shuffle a tensor (This is important for when you want to shuffle your data so the inherant data doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [5,1],
                            [8,4]])
# Shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled) # Shuffled along it's 1st dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  1],
       [ 8,  4],
       [10,  7]], dtype=int32)>

In [25]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  1],
       [ 8,  4],
       [10,  7]], dtype=int32)>

In [26]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  4],
       [ 5,  1]], dtype=int32)>

In [28]:
tf.random.set_seed = 42
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  4],
       [ 5,  1],
       [10,  7]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed generation : https://www.tensorflow.org/api_docs/python/tf/random/set_seed
and practice writing 5 random tensors and shuffle them 